<!DOCTYPE html>
<html>
<body>
    <nav class="navbar">
        <a href="index.php">Home</a> 
        <a href="jobs.php">Job Openings</a> 
        <a href="apply.php" >Job Application</a> 
        <a href="about.php" >About us</a>
        <a href="manage.php" >Manage</a>
        <div class="contact">
            <a href="#">Contact</a>
            <ul class="submenu">
                <li><a href="mailto:info@alimson.com">Email Us</a></li>
                <li><a href="tel:+60123456789">Call Us</a></li>
                <li><a href="contact.html">Contact Form</a></li>
            </ul>
        </div>
    </nav>
</body>
</html>